# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iBach' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.7'
    pod 'Unbox'
    pod 'AlamofireImage'

  # Pods for iBach

  target 'iBachTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iBachUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
